Add files via upload
Poison-Berries/junior-course-tasks pull request #1
Opened 2021-04-25 17:33 UTC by VladimirPapazov88

2021-04-25 18:53 UTC, kolayne requested changes
Thanks for the PR. I have looked through your code and left some comments. Besides, there are some changes you need to make to it before it is approved:
- In your HTML snippets you have `<link>`s inside of `<body>`s. However, it's suggested that `<link>`s only appear in `<head>`. Fix it, please (you might want to place all your snippets in actual HTML files with proper HTML code (`<html>` tags and so on), put them all in a directory, and use them from your code as static files)
- Place all your files by the following path `/CATEGORY/TOPIC-YEAR[-OTHERINFO]`, for example, `/web/cookies-2021` or `/crypto/base-2021-exam`
- Added a `README.md` file inside your folder with at least a brief explanation of what is in your folder and how to run it (i.e. libraries to install and a command to run your task) - see current directories as examples (they're in Russian, unfortunately).

I will update the main repository's readme to provide information about how contributions should be formatted (directories, readme, ...).

And remember to give commits proper names!

2021-04-25 18:53 UTC, kolayne commented on cookiesCTF/main.py
> +		<b><a href="/1" class="link">Task №1(Update page)</a>
```suggestion
		<b><a href="/1" class="link">Task №1 (Refresh page)</a>
```

2021-04-25 18:53 UTC, kolayne commented on cookiesCTF/main.py
> +		<h1 class=".header1">Select a task or check flag:</h1>
Did you mean to place a dot here?

2021-04-25 18:53 UTC, kolayne commented on cookiesCTF/main.py
> +		</body>'''
What's about `else`? You do not respond if the cookie is not what you expect? I think you should behave in the same way as if the cookie was "no"

2021-04-25 18:53 UTC, kolayne commented on cookiesCTF/styles.css
> +}
Consider adding a new line here

2021-04-25 19:25 UTC, kolayne commented
I have added the section for contributors to the repository's README. Please, consider reading it and make sure you have everything requested in your PR

2021-04-26 13:45 UTC, closed without merging

2021-04-26 13:45 UTC, VladimirPapazov88 commented
Okay

2021-04-26 14:20 UTC, kolayne commented
Please, note that you don't have to create a new Pull Request when you want to update files you're requesting to merge: you can not only push to your branch but also force-push commits if you need to amend something you have already pushed